### ISSUE TITLE
replace

### ISSUE THREAD

**Issue by vicentequintero** [danila-shirkov/exercises-html#22]
https://github.com/danila-shirkov/exercises-html/blob/5546742183532152dc3f71edca709c31226be705/exercises-html_all_link.txt#L110C10-L110C54

replace for another microtest in SPA or ENG

**Comment by yana-fesenko** [comment]
@vicentequintero какую бы ты ссылку предложил?

**Comment by vicentequintero** [comment]
Думаю лучше оставим как есть.

**Comment by yana-fesenko** [comment]
@vicentequintero ты предлагаешь оставить на русском языке

**Comment by vicentequintero** [comment]
Мне открывается на английском))

**Comment by yana-fesenko** [comment]
@vicentequintero https://webmaster.yandex.**ru**/tools/microtest/ - сайт на русском языке, посмотри какой руть открывается у тебя

**Comment by vicentequintero** [comment]
@yana-fesenko на английском HTML5 defines many named entities, references to which act as mnemonic aliases for certain Unicode characters.[1] The HTML5 specification does not allow users to define additional entities, as it no longer accepts any DTD to be referenced or extended inside HTML documents (this is still needed in XHTML, which is based on stricter XML parsing rules but allows referencing or defining a DTD in the document header, because XML does not predefine most HTML entities).

In the table below, the "Standard" column indicates the first version of the HTML DTD that defines the character entity reference, and indicates characters that are predefined in XML without needing any DTD. To use one of these character entity references in an HTML or XML document, enter an ampersand followed by the entity name, and a semicolon (mandatory in XML, and strongly recommended in HTML for all entities, even if HTML allows omitting the semicolon only from some entities indicated below by [b]), e.g., enter &copy; for the copyright symbol ©.

https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references

https://developer.mozilla.org/en-US/docs/Web/HTML/Element

**Comment by yana-fesenko** [comment]
@vicentequintero этот сайт открывается на русском. вот его версия на исп https://validator.schema.org/?hl=es
поставь пожалуйста на исп
@vicentequintero Por favor cierra el issue cuando ya cambias el enlace

**Comment by yana-fesenko** [comment]
@vicentequintero no está la enlace
